name: txapi-build

on:
  # Automatically trigger it there are changes in repo
  push:
    branches: [ '*' ]
    paths-ignore:
      - '.github/dependabot.yaml'
  pull_request:
    branches: [ main ]

  # Allow manually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: |
            btnguyen2k/txapi
          file: ./Dockerfile
          context: ./
